"""Domain enums for roles, statuses, and types."""

from enum import Enum


class UserRole(str, Enum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ADMIN = "ADMIN"
    SHOPKEEPER = "SHOPKEEPER"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    PENDING_VERIFICATION = "PENDING_VERIFICATION"
    BLOCKED = "BLOCKED"


class BusinessType(str, Enum):
    BOUTIQUE = "BOUTIQUE"
    RETAIL_STORE = "RETAIL_STORE"
    CHAIN_STORE = "CHAIN_STORE"
    WHOLESALER = "WHOLESALER"
    ONLINE_RETAILER = "ONLINE_RETAILER"
    OTHER = "OTHER"


class ProductStatus(str, Enum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"
    OUT_OF_STOCK = "OUT_OF_STOCK"
    DISCONTINUED = "DISCONTINUED"


class GenderCategory(str, Enum):
    WOMEN = "WOMEN"
    MEN = "MEN"
    KIDS = "KIDS"
    UNISEX = "UNISEX"


class InventoryAction(str, Enum):
    STOCK_IN = "STOCK_IN"
    STOCK_OUT = "STOCK_OUT"
    STOCK_ADJUSTMENT = "STOCK_ADJUSTMENT"
    ORDER_RESERVED = "ORDER_RESERVED"
    ORDER_RELEASED = "ORDER_RELEASED"
    ORDER_FULFILLED = "ORDER_FULFILLED"


class OrderStatus(str, Enum):
    CART = "CART"
    ORDER_PLACED = "ORDER_PLACED"
    PENDING_CONFIRMATION = "PENDING_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    PROCESSING = "PROCESSING"
    PACKED = "PACKED"
    SHIPPED = "SHIPPED"
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    PAID = "PAID"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class PaymentMethod(str, Enum):
    COD = "COD"
    BANK_TRANSFER = "BANK_TRANSFER"
    UPI = "UPI"
    RAZORPAY = "RAZORPAY"
    STRIPE = "STRIPE"
    CREDIT_ACCOUNT = "CREDIT_ACCOUNT"


class RequirementStatus(str, Enum):
    PENDING = "PENDING"
    REVIEWING = "REVIEWING"
    QUOTED = "QUOTED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CONVERTED_TO_ORDER = "CONVERTED_TO_ORDER"
    COMPLETED = "COMPLETED"


class NotificationType(str, Enum):
    NEW_ORDER = "NEW_ORDER"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    ORDER_SHIPPED = "ORDER_SHIPPED"
    ORDER_DELIVERED = "ORDER_DELIVERED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    ORDER_STATUS = "ORDER_STATUS"
    REQUIREMENT_UPDATE = "REQUIREMENT_UPDATE"
    LOW_STOCK = "LOW_STOCK"
    ADMIN_MESSAGE = "ADMIN_MESSAGE"
    SYSTEM_ALERT = "SYSTEM_ALERT"
